import { studentsTable, lessonsTable } from '../config/airtable';

// Helper function to format student records
const formatStudent = (record) => ({
  id: record.id,
  name: record.fields.Name || '',
  email: record.fields.Email || null,
  phone: record.fields.Phone || null,
  grade: record.fields.Grade || null,
  guardianName: record.fields.GuardianName || null,
  guardianPhone: record.fields.GuardianPhone || null,
  createdAt: record.fields.CreatedAt || null,
});

// Helper function to format lesson records
const formatLesson = (record) => {
  return {
    id: record.id,
    reference: record.fields.Reference || null,
    studentId: record.fields.Student?.[0] || null,
    date: record.fields.Date || null,
    duration: record.fields.Duration || 0,
    subject: record.fields.Subject || null,
    notes: record.fields.Notes || null,
    isPaid: record.fields.IsPaid || false,
    amountPaid: record.fields.AmountPaid || null,
    amountDue: record.fields.AmountDue || null,
    createdAt: record.fields.CreatedAt || null,
  };
};

// Students API
export const studentsAPI = {
  getAll: async () => {
    const records = await studentsTable
      .select({
        sort: [{ field: 'CreatedAt', direction: 'desc' }],
      })
      .all();

    // Fetch all lessons once (more efficient than querying per student)
    let allLessons = [];
    try {
      const lessonRecords = await lessonsTable
        .select({
          sort: [{ field: 'Date', direction: 'desc' }],
        })
        .all();
      allLessons = lessonRecords.map((l) => formatLesson(l));
      console.log(`Fetched ${allLessons.length} total lessons`);
    } catch (error) {
      console.error('Error fetching lessons:', error);
    }

    const students = records.map((record) => {
      const student = formatStudent(record);
      // Filter lessons for this student
      student.lessons = allLessons.filter((lesson) => {
        return lesson.studentId === record.id;
      });
      console.log(`Student ${student.name}: ${student.lessons.length} lessons`);
      return student;
    });

    return students;
  },

  getById: async (id) => {
    const record = await studentsTable.find(id);
    const student = formatStudent(record);

    // Fetch all lessons and filter for this student (more reliable than filterByFormula)
    try {
      const lessonRecords = await lessonsTable
        .select({
          sort: [{ field: 'Date', direction: 'desc' }],
        })
        .all();

      // Filter lessons where Student field contains this student's ID
      student.lessons = lessonRecords
        .filter((l) => {
          const studentIds = l.fields.Student || [];
          return studentIds.includes(id);
        })
        .map((l) => formatLesson(l));
    } catch (error) {
      console.error('Error fetching lessons for student:', error);
      student.lessons = [];
    }

    return student;
  },

  create: async (data) => {
    // Build fields object, only including non-empty values
    const fields = {
      Name: data.name,
    };

    // Only add optional fields if they have values
    if (data.email) fields.Email = data.email;
    if (data.phone) fields.Phone = data.phone;
    if (data.grade) fields.Grade = data.grade;
    if (data.guardianName) fields.GuardianName = data.guardianName;
    if (data.guardianPhone) fields.GuardianPhone = data.guardianPhone;

    // Note: CreatedAt is auto-generated by Airtable, don't set it manually
    const record = await studentsTable.create(fields);
    return formatStudent(record);
  },

  update: async (id, data) => {
    // Build fields object
    const fields = {
      Name: data.name,
    };

    // Only add optional fields if they have values
    if (data.email !== undefined) fields.Email = data.email || '';
    if (data.phone !== undefined) fields.Phone = data.phone || '';
    if (data.grade !== undefined) fields.Grade = data.grade || '';
    if (data.guardianName !== undefined) fields.GuardianName = data.guardianName || '';
    if (data.guardianPhone !== undefined) fields.GuardianPhone = data.guardianPhone || '';

    // Note: UpdatedAt field has been removed, don't set it
    const record = await studentsTable.update(id, fields);
    return formatStudent(record);
  },

  delete: async (id) => {
    await studentsTable.destroy(id);
    return { message: 'Student deleted successfully' };
  },
};

// Lessons API
export const lessonsAPI = {
  getAll: async () => {
    const records = await lessonsTable
      .select({
        sort: [{ field: 'Date', direction: 'desc' }],
      })
      .all();

    const lessons = await Promise.all(
      records.map(async (record) => {
        const lesson = formatLesson(record);
        // Fetch student info
        if (lesson.studentId) {
          try {
            const studentRecord = await studentsTable.find(lesson.studentId);
            lesson.student = {
              id: lesson.studentId,
              name: studentRecord.fields.Name || '',
            };
          } catch (err) {
            console.error('Error fetching student:', err);
          }
        }
        return lesson;
      })
    );

    return lessons;
  },

  getById: async (id) => {
    const record = await lessonsTable.find(id);
    const lesson = formatLesson(record);

    // Fetch student info
    if (lesson.studentId) {
      try {
        const studentRecord = await studentsTable.find(lesson.studentId);
        lesson.student = {
          id: lesson.studentId,
          name: studentRecord.fields.Name || '',
        };
      } catch (err) {
        console.error('Error fetching student:', err);
      }
    }

    return lesson;
  },

  create: async (data) => {
    // Fetch student name for the record
    let studentName = '';
    try {
      const studentRecord = await studentsTable.find(data.studentId);
      studentName = studentRecord.fields.Name || '';
    } catch (err) {
      console.error('Error fetching student:', err);
    }

    // Generate auto-reference number
    let reference = '';
    try {
      const allLessons = await lessonsTable.select().all();
      const lessonNumber = allLessons.length + 1;
      reference = `LESSON-${String(lessonNumber).padStart(4, '0')}`;
    } catch (err) {
      console.error('Error generating reference:', err);
      const timestamp = Date.now().toString().slice(-6);
      reference = `LESSON-${timestamp}`;
    }

    // Note: CreatedAt is auto-generated by Airtable, don't set it manually
    const record = await lessonsTable.create({
      Reference: reference,
      Student: [data.studentId],
      StudentName: studentName,
      Date: data.date,
      Duration: parseInt(data.duration),
      Subject: data.subject || '',
      Notes: data.notes || '',
      IsPaid: data.isPaid || false,
      AmountPaid: data.amountPaid ? parseFloat(data.amountPaid) : null,
      AmountDue: data.amountDue ? parseFloat(data.amountDue) : null,
    });

    const lesson = formatLesson(record);
    lesson.student = {
      id: data.studentId,
      name: studentName,
    };

    return lesson;
  },

  update: async (id, data) => {
    const updateData = {};

    if (data.date) updateData.Date = data.date;
    if (data.duration !== undefined) updateData.Duration = parseInt(data.duration);
    if (data.subject !== undefined) updateData.Subject = data.subject || '';
    if (data.notes !== undefined) updateData.Notes = data.notes || '';
    if (data.isPaid !== undefined) updateData.IsPaid = data.isPaid;
    if (data.amountPaid !== undefined) {
      updateData.AmountPaid = data.amountPaid ? parseFloat(data.amountPaid) : null;
    }
    if (data.amountDue !== undefined) {
      updateData.AmountDue = data.amountDue ? parseFloat(data.amountDue) : null;
    }
    if (data.studentId) {
      updateData.Student = [data.studentId];
      // Fetch student name
      try {
        const studentRecord = await studentsTable.find(data.studentId);
        updateData.StudentName = studentRecord.fields.Name || '';
      } catch (err) {
        console.error('Error fetching student:', err);
      }
    }

    // Note: UpdatedAt field has been removed, don't set it
    const record = await lessonsTable.update(id, updateData);
    const lesson = formatLesson(record);

    // Fetch student info
    if (lesson.studentId) {
      try {
        const studentRecord = await studentsTable.find(lesson.studentId);
        lesson.student = {
          id: lesson.studentId,
          name: studentRecord.fields.Name || '',
        };
      } catch (err) {
        console.error('Error fetching student:', err);
      }
    }

    return lesson;
  },

  delete: async (id) => {
    await lessonsTable.destroy(id);
    return { message: 'Lesson deleted successfully' };
  },
};

// Stats API
export const statsAPI = {
  getStats: async () => {
    const students = await studentsTable.select().all();
    const lessons = await lessonsTable.select().all();

    const totalStudents = students.length;
    const totalLessons = lessons.length;
    const paidLessons = lessons.filter((l) => l.fields.IsPaid === true).length;
    const unpaidLessons = totalLessons - paidLessons;

    const totalRevenue = lessons
      .filter((l) => l.fields.IsPaid === true && l.fields.AmountPaid)
      .reduce((sum, l) => sum + (l.fields.AmountPaid || 0), 0);

    return {
      totalStudents,
      totalLessons,
      paidLessons,
      unpaidLessons,
      totalRevenue,
    };
  },
};